### PR TITLE
通风14-2班高峰的作业

### PR DESCRIPTION
**Pull request by gaofengxixixi**
老师麻烦看看我的作业写得是否正确

### CODE REVIEW

**Comment by anheihb03dlj** [comment]
没有问题，再补一个作业，咱们要求是7个任选2个，加油吧~

**Comment by anheihb03dlj** [comment]
忘了个事，你写的代码py文件要按照test0-0.py这个模板文件的格式来写

**Comment by anheihb03dlj** [comment]
我去你的仓库看了下，代码呢？都删掉了？

**Comment by gaofengxixixi** [comment]
我的那个文件格式不是不对吗？我删掉重新写一遍再上传啊！~！~！~

**Comment by anheihb03dlj** [comment]
哦哦，那赶紧上传吧。。。嘿嘿

**Comment by anheihb03dlj** [comment]
把代码改好后，按照教程的第11步重新操作一遍，不需要重新创建新的pull-request，只要你那边提交和上传了，我这边就能看到你最新的作业和代码

**Comment by gaofengxixixi** [comment]
Pushing to https://github.com/gaofengxixixi/learn-python.git
To https://github.com/gaofengxixixi/learn-python.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/gaofengxixixi/learn-python.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.



老师 这什么意思啊！~我做好了 但是传不上去！~~~~~气人！

**Pull request closed without merging**
